### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by GenericProgrammer1234** [Vyxal/VyxalBot2#119]
With documentation in the code it will be much easier to figure out what stuff does, now as the Master Programmer™ I am it totally takes me very little time to figure out what any piece of code does including this one, however it would be valuable to future more inexperienced members and it will just make actually coding faster.

**Comment by GenericProgrammer1234** [comment]
(Testing if VyxalBot reports comments in issues because idk)

**Comment by GingerIndustries** [comment]
Is this issue relating to version 2 or version 3?

**Comment by GingerIndustries** [comment]
While I intend to document the internals of the bot eventually, it's not very high on my to-do list right now.

**Comment by GenericProgrammer1234** [comment]
Alright. I could help?

**Comment by GingerIndustries** [comment]
> Alright. I could help?

I'd prefer it if people I know from the Vyxal org helped out with this; I only recall you from CGCC chat, and my memories aren't all that fond.
