### ISSUE TITLE
Add safeguards to what the Vyxal Bot says

### ISSUE THREAD

**Issue by PlaceReporter99** [Vyxal/VyxalBot2#90]
I ran the command `!!/status tingly` and for some reason, [it unzipped my pants. (The message was removed)](https://chat.stackexchange.com/transcript/message/63900153#63900153) Adding this safeguard would make sure this does not happen again.

**Comment by nayakrujul** [comment]
Looks like we can't do much about it as the message is coming from uwuipy: https://github.com/Vyxal/VyxalBot2/blob/053926899cd6f3e5cbabe89468641da45e39f57e/vyxalbot2/__init__.py#L328

**Comment by GingerIndustries** [comment]
I'm going to be fixing this at some point, probably by forking uwuipy.
